name: Qt6 GUI Application CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: "6.2.4"

jobs:
  build_msvc:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      id: install-qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: ${{ env. QT_VERSION }}
        arch: Windows
        target: desktop

    - name: Configure CMake (MSVC)
      shell: cmd
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64"

    - name: Build with MSBuild (MSVC)
      shell: cmd
      run: |
        msbuild build\qt_test.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64
